### ISSUE TITLE
bug: panic in docker container

### ISSUE THREAD

**Issue by ymtdzzz** [ymtdzzz/otel-tui#86]
Dockerfile

```dockerfile
#
# Build
#
FROM golang:1.22 AS builder

ENV CGO_ENABLED=0
ENV GOOS=linux
WORKDIR /build

COPY . .

RUN go build -o main ./...

#
# Deploy
#
FROM gcr.io/distroless/static-debian12:latest

WORKDIR /

COPY --from=builder /build/main /main

USER nonroot

CMD [ "/main" ]
```

`docker run` causes panic on the initializing phase:

```
2024-06-29T12:44:21.868Z	info	service@v0.103.0/service.go:115	Setting up own telemetry...
2024-06-29T12:44:21.868Z	info	service@v0.103.0/telemetry.go:96	Serving metrics	{"address": ":8888", "level": "Normal"}
2024-06-29T12:44:21.868Z	info	exporter@v0.103.0/exporter.go:280	Development component. May change in the future.	{"kind": "exporter", "data_type": "logs", "name": "tui"}
panic: clipboard: cannot use when CGO_ENABLED=0

goroutine 1 [running]:
golang.design/x/clipboard.initialize(...)
	/go/pkg/mod/golang.design/x/clipboard@v0.7.0/clipboard_nocgo.go:9
golang.design/x/clipboard.Init.func1()
	/go/pkg/mod/golang.design/x/clipboard@v0.7.0/clipboard.go:107 +0x25
sync.(*Once).doSlow(0xc0000508a0?, 0xc00073dbd0?)
	/usr/local/go/src/sync/once.go:74 +0xc2
sync.(*Once).Do(...)
	/usr/local/go/src/sync/once.go:65
golang.design/x/clipboard.Init()
	/go/pkg/mod/golang.design/x/clipboard@v0.7.0/clipboard.go:106 +0x2c
github.com/ymtdzzz/otel-tui/tuiexporter/internal/tui/component.(*TUIPages).createDebugLogPage(0xc000212a20?)
	/build/tuiexporter/internal/tui/component/page.go:360 +0xea
github.com/ymtdzzz/otel-tui/tuiexporter/internal/tui/component.(*TUIPages).registerPages(0xc00049da00, 0xc000001080)
	/build/tuiexporter/internal/tui/component/page.go:80 +0x25
github.com/ymtdzzz/otel-tui/tuiexporter/internal/tui/component.NewTUIPages(0xc000001080, 0xc000336510)
	/build/tuiexporter/internal/tui/component/page.go:40 +0x2d1
github.com/ymtdzzz/otel-tui/tuiexporter/internal/tui.NewTUIApp(0xc000001080)
	/build/tuiexporter/internal/tui/tui.go:25 +0xf6
github.com/ymtdzzz/otel-tui/tuiexporter.newTuiExporter(0x0?)
	/build/tuiexporter/exporter.go:20 +0x18f
github.com/ymtdzzz/otel-tui/tuiexporter.createLogs.func1()
	/build/tuiexporter/factory.go:58 +0x17
github.com/ymtdzzz/otel-tui/tuiexporter/internal/sharedcomponent.(*Map[...]).LoadOrStore(0x1368ac0, 0x1c44000, 0xc00073e090, 0xc000536de0)
	/build/tuiexporter/internal/sharedcomponent/sharedcomponent.go:47 +0x204
github.com/ymtdzzz/otel-tui/tuiexporter.createLogs({0x13667b8, 0x1c44000}, {{{{0xc00011f798, 0x3}}, {0x0, 0x0}}, {0xc0004b0f80, {0x1360a20, 0xc000140870}, {0x135ee88, ...}, ...}, ...}, ...)
	/build/tuiexporter/factory.go:55 +0x115
go.opentelemetry.io/collector/exporter.CreateLogsFunc.CreateLogsExporter(...)
	/go/pkg/mod/go.opentelemetry.io/collector/exporter@v0.103.0/exporter.go:129
go.opentelemetry.io/collector/exporter.(*Builder).CreateLogs(0xc000336020, {0x13667b8, 0x1c44000}, {{{{0xc00011f798, 0x3}}, {0x0, 0x0}}, {0xc0004b0f80, {0x1360a20, 0xc000140870}, ...}, ...})
	/go/pkg/mod/go.opentelemetry.io/collector/exporter@v0.103.0/exporter.go:266 +0x13d
go.opentelemetry.io/collector/service/internal/graph.(*exporterNode).buildComponent(0xc000127ae0, {0x13667b8, 0x1c44000}, {0xc0004b0b80, {0x1360a20, 0xc000140870}, {0x135ee88, 0xc00050f6c0}, 0x1, {0xc00050f4a0, ...}, ...}, ...)
	/go/pkg/mod/go.opentelemetry.io/collector/service@v0.103.0/internal/graph/nodes.go:193 +0x270
go.opentelemetry.io/collector/service/internal/graph.(*Graph).buildComponents(0xc000088e40, {0x13667b8, 0x1c44000}, {{0xc0004b0b80, {0x1360a20, 0xc000140870}, {0x135ee88, 0xc00050f6c0}, 0x1, {0xc00050f4a0, ...}, ...}, ...})
	/go/pkg/mod/go.opentelemetry.io/collector/service@v0.103.0/internal/graph/graph.go:312 +0x514
go.opentelemetry.io/collector/service/internal/graph.Build({0x13667b8, 0x1c44000}, {{0xc0004b0b80, {0x1360a20, 0xc000140870}, {0x135ee88, 0xc00050f6c0}, 0x1, {0xc00050f4a0, 0xc00011f940}, ...}, ...})
	/go/pkg/mod/go.opentelemetry.io/collector/service@v0.103.0/internal/graph/graph.go:84 +0x450
go.opentelemetry.io/collector/service.(*Service).initExtensionsAndPipeline(_, {_, _}, {{{0x11d06f3, 0x8}, {0x11f35f3, 0x27}, {0x11cf1e5, 0x7}}, 0xc00003edc0, ...}, ...)
	/go/pkg/mod/go.opentelemetry.io/collector/service@v0.103.0/service.go:288 +0x2a8
go.opentelemetry.io/collector/service.New({_, _}, {{{0x11d06f3, 0x8}, {0x11f35f3, 0x27}, {0x11cf1e5, 0x7}}, 0xc00003edc0, 0xc000336000, ...}, ...)
	/go/pkg/mod/go.opentelemetry.io/collector/service@v0.103.0/service.go:145 +0x948
go.opentelemetry.io/collector/otelcol.(*Collector).setupConfigurationComponents(0xc0004947e0, {0x13667b8, 0x1c44000})
	/go/pkg/mod/go.opentelemetry.io/collector/otelcol@v0.103.0/collector.go:192 +0x668
go.opentelemetry.io/collector/otelcol.(*Collector).Run(0xc0004947e0, {0x13667b8, 0x1c44000})
	/go/pkg/mod/go.opentelemetry.io/collector/otelcol@v0.103.0/collector.go:277 +0x55
main.newCommand.func1(0xc00048e608, {0x11cf22b?, 0x7?, 0x11cbfb8?})
	/build/main.go:92 +0x36f
github.com/spf13/cobra.(*Command).execute(0xc00048e608, {0xc00003e0a0, 0x0, 0x0})
	/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:983 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0xc00048e608)
	/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
main.runInteractive({0x123b510, {{0x11d06f3, 0x8}, {0x11f35f3, 0x27}, {0x11cf1e5, 0x7}}, 0x0, {{{0x0, 0x0, ...}, ...}}, ...})
	/build/main.go:37 +0x5d
main.run(...)
	/build/main_others.go:10
main.main()
	/build/main.go:29 +0x125
```

**Comment by ymtdzzz** [comment]
related: https://github.com/golang-design/clipboard/issues/57
